### ISSUE TITLE
Request support for Android 11

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#34]
Hi,

We notice that the HelpCruch SDK requires access to the device's storage (mostly for picking files).
In Android 11 [the MANAGE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE) permission must be set and handled before 5 May, 2021 to support devices running Android 11.

[In this link](https://support.google.com/googleplay/android-developer/answer/10467955#zippy=) there's more info about that.

**Comment by TalbotGooday** [comment]
Hello! In newer versions of SDK, we will only use the built-in image picker, which will be satisfied with the current permissions. We will use the default intent for file selection. In older versions, everything will remain the same. Therefore, there is no need to add this permission :+1: 

You can check these changes in the latest SNAPSHOT version.

Please, add this to the root gradle:
```
allprojects {
    repositories {
        ...
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}
```
and here is the snapshot build:
```
implementation('com.helpcrunch:chat-sdk:3.0.8-rc.03-s.84-SNAPSHOT')
```

**Comment by Mahmoood** [comment]
What we're currently using is `com.helpcrunch:chat-sdk:3.0.7`. 
We found some memory-related issues in the later snapshots.

So, what are the changes that `implementation('com.helpcrunch:chat-sdk:3.0.8-rc.03-s.84-SNAPSHOT')` include?

How does it handle accessing files on Android 11?

**Comment by TalbotGooday** [comment]
I am 100% sure that you have not used a **snapshot** of the version before, if only because they are test ones and we provide them to clients only as an acquaintance or in case of solving urgent tasks related to the need for testing on the client side :)

In the version that I offered you, we **refuse to use low-level access** to files in favor of access through the **content provider and intent requests** on Android R. 

This version also has improved stability, fixed bugs and added functionality for previewing articles from the knowledge base. The **pre-form** has also been **redesigned**, which can now be changed on the fly using the Android application settings in our web-console.

I **strongly discourage** using this version in production because a stable version is coming soon. But you can review the changes and prepare your application for these changes.

**Comment by Mahmoood** [comment]
Thanks for the response.

Sorry, I wasn't a snapshot, it was an alpha version of `3.0.8`

We'll give the snapshot version a try.

When do you expect the stable version will be published?

**Comment by TalbotGooday** [comment]
> We'll give the snapshot version a try.

Awesome! :+1: 

> When do you expect the stable version will be published?

On Monday

**Comment by TalbotGooday** [comment]
Hi there! The v3.0.8 is already available :+1:

**Comment by Mahmoood** [comment]
Thanks for the update.

Where can I get the release notes of that version?
I mean what's new in that version comparing with the `3.0.7`

**Comment by TalbotGooday** [comment]
Here it is: [changelog](https://github.com/helpcrunch/android-sdk-demo/blob/master/CHANGELOG.md) :+1:

**Comment by Mahmoood** [comment]
I didn't expect that it's there because the latest release tag is still `3.0.7`.

**Comment by TalbotGooday** [comment]
Yes, you are right, because I have not had time to update them yet :)

**Comment by Mahmoood** [comment]
Thanks a lot 👍

**Comment by TalbotGooday** [comment]
Thank you too! Have a good day :)
