### ISSUE TITLE
Notifications don't appear when the app is killed

### ISSUE THREAD

**Issue by Mahmoood** [helpcrunch/android-sdk-demo#42]
Hi,

Starting from SDK version 3.0.8+ the notifications stop working.
When sending a message from the HelpCrunch console to a user when the Android client app isn't open nothing happens.
I mean the notification doesn't appear.

I was working on version 3.0.7.

**Comment by TalbotGooday** [comment]
On v3.0.8+ it works the same as on the version 3.0.7. Displaying notifications in the background depends only on the firebase and the system and has never been controlled by our SDK. The code for working with firebase, except for version updates, has not changed, so I dare to assume that notifications are not shown due to the low priority of your application in the system

**Comment by Mahmoood** [comment]
>  low priority of your application in the system

That's not the case, because it's a new installation on the system.
I tried that on multiple devices, on two apps, and it doesn't work.

**Comment by TalbotGooday** [comment]
We also ran tests on 6 different devices and everything worked. This is not a new bug. This is how firebase works. If you did not forget to specify the firebase key in our console, added the firebase data in your application, then everything will work, but not always stable and not 'cause of us. 
If you search the web for this problem, you will find that it is quite common. Unfortunately, there is nothing we can do about it. 
All I can advise is to clear the application data. It often works

**Comment by Mahmoood** [comment]
Actually, I tried uninstalling the whole app and installing it again.
But that doesn't help.

Why don't you (the microservice that handles sending notifications) send message notifications instead of high priority notifications?

I think the message and the body are known, no need for any hidden data inside.
Because you know that's out of Firebase's restriction if that's the issue (I mean no limitations or blocking using message notifications).

**Comment by TalbotGooday** [comment]
Yes, I understand what you are talking about, but there are a couple of points:
1. Reinstalling the application often does not help, because the data cache is also stored on the phone and has also been stored in Google services for a very long time. So we need to clear the cache manually
2. The firebase receives and sends messages using Google services, which in turn transmit the intent with the data to the desired application. The problem is that the Android system is blocking this intent, since the application is not a priority for the system itself

We can bypass the system's limitations by running some lightweight service through the AlarmManager, which will show the system that the application is running and alive. But if there are many such services in the system, then this will affect the battery charge.
We are looking for ways to solve this problem. But so far we are addicted to firebases and face the same problems as the rest of the world.
